version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
    versions:
    - "> 2.10.3"
  - dependency-name: io.fabric8:openshift-client
    versions:
    - ">= 4.2.1.a, < 4.2.2"
  - dependency-name: org.jboss.resteasy:resteasy-client
    versions:
    - "> 3.11.2.Final"
  - dependency-name: org.jboss.resteasy:resteasy-client
    versions:
    - ">= 4.a, < 5"
